### ISSUE TITLE
Error handling for broken connections

### ISSUE THREAD

**Issue by Linuus** [ostinelli/apnotic#129]
Hi!

We're trying out your gem to send VoIP notifications, using Sidekiq. We are having some issues though with broken connections.

At first we were raising an error in the `connection.on(:error) {}` callback, like this:

```rb
      Apnotic::ConnectionPool.new(connection_config, size: 5) do |connection|
        connection.on(:error) do |exception|
          raise(PushNotification::Error, "Production APNs connection error: #{exception}")
        end
      end
```

That was a really bad idea since it crashed all of Sidekiq making it restart. We fixed this and now we're just reporting to our error service instead.

```rb
      Apnotic::ConnectionPool.new(connection_config, size: 5) do |connection|
        connection.on(:error) do |exception|
          Sentry.capture_exception(exception)
        end
      end
```

Now, occasionally we get this error reported:

```
Errno::ECONNRESET: Connection reset by peer
  from openssl (3.2.0) lib/openssl/buffering.rb:211:in `sysread_nonblock'
  from openssl (3.2.0) lib/openssl/buffering.rb:211:in `read_nonblock'
  from net-http2 (0.18.5) lib/net-http2/client.rb:145:in `block in socket_loop'
  from net-http2 (0.18.5) lib/net-http2/client.rb:142:in `loop'
  from net-http2 (0.18.5) lib/net-http2/client.rb:142:in `socket_loop'
  from net-http2 (0.18.5) lib/net-http2/client.rb:114:in `block (2 levels) in ensure_open'
```

It's reported in the callback and then 60s later we get a timeout here:

```rb
    connection_pool(ios_voip_push_token).with do |connection|
      response = connection.push(apnotic_notification(notification, ios_voip_push_token))
      raise(TimeoutError) if response.nil?
      [...]
    end
```

I guess we can pass a shorter timeout to the `push` method to lower this timeout, since it seems fairly high.

Anyway, when this happened it started happening a lot. Almost all our pushes got this connection reset error. Our push jobs are not retried, but I don't think this would help either since the connections seems to not be "healed".

Could there be an issue where connections are stuck in a broken state? Or are we supposed to handle these errors differently?

**Comment by avanrielly** [comment]
This happens for us a lot too.  We are using push notifications to send print messages to iPads and the connection periodically is reset and we end up having to wait the timeout for it to fail before we can try it again.  This is causing a poor experience for our clients.  

Is there a way to guarantee the connection is still open before trying to send a new push notification?

**Comment by Jason733i** [comment]
I'm experiencing this error after migrating our AWS VPC from an EC2 instance used as a NAT to the AWS NAT Gateway. With this gem, there's an implicit expectation that every hop between your application and the destination of the request would keep a connection open indefinitely. However, this causes issues, for example, when you have a NAT that only maintains connections for up to 350 seconds.

I also noticed that setting an explicit timeout on the `Connection` seems to have no affect. It alway timed out at 60 seconds no matter what I tried.

Instead of fighting with the underlying http2 client's code, I decided to implement an `ExpiryTimedStack` that tracks the expiration time of a connection and will cull the expired connections ensuring only valid working connections are returned. 

Below is the patch code I'm using to get around this issue. If someone wanted to submit a PR based on this, please be my guest. Otherwise, use at your own risk!

```ruby
require "timeout"
require "connection_pool"

# A TimedStack that expires stored connections after a given duration.
class ConnectionPool::ExpiryTimedStack < ConnectionPool::TimedStack
  # +expiry_duration+ is the number of seconds after which a connection is considered expired.
  def initialize(size = 0, expiry_duration:, &block)
    super(size, &block)
    @expiry_duration = expiry_duration
  end

  # Override pop to handle the case where fetch_connection returns nil due to expiry.
  def pop(timeout = 0.5, options = {})
    options, timeout = timeout, 0.5 if Hash === timeout
    timeout = options.fetch :timeout, timeout

    deadline = current_time + timeout
    @mutex.synchronize do
      loop do
        raise ConnectionPool::PoolShuttingDownError if @shutdown_block

        if connection_stored?(options)
          connection = fetch_connection(options)
          # Only return if a valid connection is found.
          return connection if connection
          # If fetch_connection returned nil because of expiry, the pool was flushed.
          # Continue the loop to attempt creating a new connection.
        end

        connection = try_create(options)
        return connection if connection

        to_wait = deadline - current_time
        raise ConnectionPool::TimeoutError, "Waited #{timeout} sec" if to_wait <= 0
        @resource.wait(@mutex, to_wait)
      end
    end
  end

  private

  # Override to wrap the connection object with its expiry timestamp.
  def store_connection(obj, options = nil)
    expiry_time = current_time + @expiry_duration
    @que.push({ object: obj, expiry: expiry_time })
  end

  # Override to check the expiry of the connection.
  # If the popped connection is expired, clear the remaining pool and return nil.
  def fetch_connection(options = nil)
    while !@que.empty?
      item = @que.pop
      if current_time > item[:expiry]
        # The connection has expired. Flush the rest of the pool.
        shutdown_connections(options)
        return nil
      else
        return item[:object]
      end
    end
    nil
  end

  # Override shutdown to clean up our wrapped connection items.
  def shutdown_connections(options = nil)
    while !@que.empty?
      item = @que.pop
      @shutdown_block.call(item[:object]) if @shutdown_block
    end
    @created = 0
  end
end

# ExpiryConnectionPool uses ExpiryTimedStack to manage connections with an expiry.
class ExpiryConnectionPool < ConnectionPool
  DEFAULTS = { size: 5, timeout: 5, expiry_duration: 300 }

  def initialize(options = {}, &block)
    raise ArgumentError, "Connection pool requires a block" unless block
    options = DEFAULTS.merge(options)

    @size = Integer(options.fetch(:size))
    @timeout = options.fetch(:timeout)
    expiry_duration = options.fetch(:expiry_duration)

    @available = ConnectionPool::ExpiryTimedStack.new(@size, expiry_duration: expiry_duration, &block)
    @key = :"pool-#{@available.object_id}"
    @key_count = :"pool-#{@available.object_id}-count"
  end
end

module Apnotic
  class ExpiryConnectionPool
    class << self
      def new(options = {}, pool_options = {})
        raise(LocalJumpError, "a block is needed when initializing an Apnotic::ConnectionPool") unless block_given?

        ::ExpiryConnectionPool.new(pool_options) do
          connection = Apnotic::Connection.new(options)
          yield(connection)
          connection
        end
      end

      def development(options = {}, pool_options = {})
        raise(LocalJumpError, "a block is needed when initializing an Apnotic::ConnectionPool") unless block_given?

        ::ExpiryConnectionPool.new(pool_options) do
          connection = Apnotic::Connection.development(options)
          yield(connection)
          connection
        end
      end
    end
  end
end

```

**Comment by benubois** [comment]
Interesting findings! 

Exposing ping sounds fine to me, but the whole setup looks like it would require some configuration and potentially a separate process?

A solution that could repair the connection or require little to no configuration up front would be ideal, but I understand if that's not feasible. Did you try @Jason733i's connection expiring patch above? I would be curious if that also fixes it for you and if so could that be a way to have a full solution integrated into apnotic.

Thank you.

**Comment by mmalek-sa** [comment]
> Did you try @Jason733i's connection expiring patch above?

Using @Jason733i  `ExpiryTimedStack` is simpler, but it has these disadvantages:

- Depending on how often middle-boxes drop idle connections, you can end up with short-lived connections. In my case, there is a proxy server that drops idle connections after 5 minutes.
- Creating a new connection to APN service when there is no healthy available connection has a slight performance penalty and can impact the end-user experience when they are waiting for a push. Keeping the connection alive doesn't have this problem.
- Apple [recommends](https://developer.apple.com/documentation/usernotifications/sending-notification-requests-to-apns#Follow-best-practices-while-sending-push-notifications-with-APNs) keeping the connections alive as long as possible (for days) using PING.

> the whole setup looks like it would require some configuration and potentially a separate process?

I'm using the main Sidekiq process and a new thread via `Concurrent::TimerTask`. It would be ideal if the gem could schedule this PING task and timer whenever we create a new connection pool.

> A solution that could repair the connection or require little to no configuration up front would be ideal.

That works, but if a middle-box drops the connection completely, what would repair mean? Creating a new connection? If that's the case, I'd prefer keeping the connection healthy using PING in the first place.

**Comment by benubois** [comment]
Ok! That all makes sense.

I think you should do what you think is best, and I'd be happy to accept anything that is better than what is there now. Priority wise I'm interested in:

- No required configuration (but it would make sense to expose configuration where necessary)
- No hard requirement on sidekiq or rails

Appreciate your work on this.
