### ISSUE TITLE
nil error when there is a connection error

### ISSUE THREAD

**Issue by danielrhodes** [ostinelli/apnotic#22]
Been seeing this in production. I assume the root cause is the connection was remotely closed, but this looks like a bug in the error handling.

```
vendor/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/connection.rb:659:in `connection_error': undefined method `message' for nil:NilClass (HTTP2::Error::ProtocolError)
    from vendor/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/connection.rb:430:in `connection_management'
    from vendor/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/connection.rb:225:in `receive'
    from vendor/bundle/ruby/2.3.0/gems/net-http2-0.12.1/lib/net-http2/client.rb:109:in `block in socket_loop'
    from vendor/bundle/ruby/2.3.0/gems/net-http2-0.12.1/lib/net-http2/client.rb:105:in `loop'
    from vendor/bundle/ruby/2.3.0/gems/net-http2-0.12.1/lib/net-http2/client.rb:105:in `socket_loop'
    from vendor/bundle/ruby/2.3.0/gems/net-http2-0.12.1/lib/net-http2/client.rb:88:in `block (2 levels) in ensure_open'

Caused: vendor/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/connection.rb:659:in `connection_error': undefined method `message' for nil:NilClass (NoMethodError)
    from vendor/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/connection.rb:430:in `connection_management'
    from vendor/bundle/ruby/2.3.0/gems/http-2-0.8.2/lib/http/2/connection.rb:225:in `receive'
    from vendor/bundle/ruby/2.3.0/gems/net-http2-0.12.1/lib/net-http2/client.rb:109:in `block in socket_loop'
    from vendor/bundle/ruby/2.3.0/gems/net-http2-0.12.1/lib/net-http2/client.rb:105:in `loop'
    from vendor/bundle/ruby/2.3.0/gems/net-http2-0.12.1/lib/net-http2/client.rb:105:in `socket_loop'
    from vendor/bundle/ruby/2.3.0/gems/net-http2-0.12.1/lib/net-http2/client.rb:88:in `block (2 levels) in ensure_open'
```

Using Apnotic 0.10.0

**Comment by ostinelli** [comment]
Thank you for the report. You might want to `bundle update` first, this has already been fixed.
Ensure to use the latest Apnotic 0.10.2 with Net-Http2 0.13.3.
