### ISSUE TITLE
EOFError: end of file reached

### ISSUE THREAD

**Issue by axelander** [ostinelli/apnotic#25]
I keep getting this issue when trying to send notifications, anyone stumpled upon this before?

```
EOFError: end of file reached
	from /Users/alexander/.rbenv/versions/2.2.3/lib/ruby/2.2.0/openssl/buffering.rb:182:in `sysread_nonblock'
	from /Users/alexander/.rbenv/versions/2.2.3/lib/ruby/2.2.0/openssl/buffering.rb:182:in `read_nonblock'
	from /Users/alexander/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/net-http2-0.13.3/lib/net-http2/client.rb:111:in `block in socket_loop'
	from /Users/alexander/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/net-http2-0.13.3/lib/net-http2/client.rb:108:in `loop'
	from /Users/alexander/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/net-http2-0.13.3/lib/net-http2/client.rb:108:in `socket_loop'
	from /Users/alexander/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/net-http2-0.13.3/lib/net-http2/client.rb:93:in `block (2 levels) in ensure_open'
```

**Comment by axelander** [comment]
My mistake, tried sending to dev environment but missed that you should use Apnotic::Connection.development 😄
