### ISSUE TITLE
Guidance on implementing async timeout

### ISSUE THREAD

**Issue by tboyko** [ostinelli/apnotic#64]
I would like to include handling for timeout situations when using `.push_async` and would appreciate some guidance on how best to accomplish this.

To provide some context, we first discovered timeout-related issues in our own project upon using Apnotic's `connection.join`. The join was never returning and there were also notifications that had been queued via `.push_async` that had not run their `on(:response)` yet. Our knee jerk solution is to wrap `.join` in a timeout block and run `.close` shortly after, whether a timeout occurs or not. 

This got me to thinking... if two notifications are sent with the async method, are they always delivered in sequence? If there is some sort of delay with sending the first one, does the second one stay `stuck`? My _guess_ is that it depends upon how the http2 streams multiplex the notifications. Is this accurate?

Ultimately, I'm hoping to find a robust way to time out these problems and retry but would greatly benefit from some insights on the best way to approach it with this library.

**Comment by ostinelli** [comment]
Can you please check if this clarifies it for you?
https://github.com/ostinelli/apnotic/pull/65

**Comment by ostinelli** [comment]
I don't understand how you can get this error being raised if you define a connection callback:

```
Socket was remotely closed
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/net-http2-0.18.0/lib/net-http2/client.rb:130:in `callback_or_raise'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/net-http2-0.18.0/lib/net-http2/client.rb:115:in `rescue in block (2 levels) in ensure_open'/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/net-http2-0.18.0/lib/net-http2/client.rb:109:in `block (2 levels) in ensure_open'
```

[This](https://github.com/ostinelli/net-http2/blob/0.18.0/lib/net-http2/client.rb#L126) should take care of not raising an error. Any ideas why you are seeing this?

On a side note, instead of your current custom way of declaring a connection you can now use:

```
  APNOTIC_POOL = Apnotic::ConnectionPool.new({
    cert_path: Rails.root.join("config", "certs", "apns_certificate.pem"),
    cert_pass: "mypass"
  }, size: 5) do |connection|
    connection.on(:error) { |exception| puts "Exception has been raised: #{exception}" }
  end
```

**Comment by maciejkowalski** [comment]
Hey @ostinelli 
I pasted old stacktrace, I already have connection callback before:
```
  # https://github.com/ostinelli/apnotic/issues/48#issuecomment-399776823
  APNOTIC_POOL = ConnectionPool.new(size: 5) do
    connection = Apnotic::Connection.new(
      cert_path: Rails.root.join(ENV.fetch('IOS_PUSH_APN_PEM_CERT'))
    )
    connection.on(:error) do |exception|
      Sidekiq.logger.error "Exception has been raised on APNS socket: #{exception.inspect}"
    end
    connection
  end
```

Right now I switched from `ConnectionPool` to 1 connection per worker and it works.

It seems to me like after connection is broken 
see https://github.com/ostinelli/apnotic/issues/73
then it doesn't reinitialize the connection inside pool and when worker tries to use it, it hangs forever.

**Comment by maciejkowalski** [comment]
> What do you mean "I pasted old stacktrace"?

That means this stacktrace:
```
Socket was remotely closed
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/net-http2-0.18.0/lib/net-http2/client.rb:130:in `callback_or_raise'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/net-http2-0.18.0/lib/net-http2/client.rb:115:in `rescue in block (2 levels) in ensure_open'/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/net-http2-0.18.0/lib/net-http2/client.rb:109:in `block (2 levels) in ensure_open'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Fixnum is deprecated
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Bignum is deprecated
```

was when, I had `ConnectionPool` without callback (and Sidekiq worker was crashing)
```ruby
class AbstractSendMobileNotificationWorker
  include Sidekiq::Worker
  sidekiq_options retry: 0

  APNOTIC_POOL = ConnectionPool.new(size: 5) do
    connection = Apnotic::Connection.new(
      cert_path: Rails.root.join(ENV.fetch('IOS_PUSH_APN_PEM_CERT'))
    )
    connection
  end
# [...]
```

After that (found info here) I added callback:
```ruby
class AbstractSendMobileNotificationWorker
  include Sidekiq::Worker
  sidekiq_options retry: 0

  # https://github.com/ostinelli/apnotic/issues/48#issuecomment-399776823
  APNOTIC_POOL = ConnectionPool.new(size: 5) do
    connection = Apnotic::Connection.new(
      cert_path: Rails.root.join(ENV.fetch('IOS_PUSH_APN_PEM_CERT'))
    )
    connection.on(:error) do |exception|
      Sidekiq.logger.error "Exception has been raised on APNS socket: #{exception.inspect}"
    end
    connection
  end
# [...]
```

Sidekiq stopped crashing when connection was closed, but I experienced issues with hanging sidekiq jobs.


> #73 has nothing to do with this.

In my experience (YMMV) if you got 2 `SocketError`s, 2 sidekiq workers were executing forever.
So I suspect it has to do with `corrupted connection` inside `ConnectionPool`

**Comment by ostinelli** [comment]
Please see if latest `1.6.0` solves your issue.

**Comment by wogg** [comment]
I'm posting this here, because it seems the same as the original poster's issue, however I am in running using a single connection in a rake task. It happens inconsistently. This is the stack that is dumped, when I interrupt a stuck process using sig TERM:

versions: (ruby 2.3.8)
```
   apnotic (1.6.0)
      connection_pool (~> 2)
      net-http2 (>= 0.18, < 2)
```

trace reported when interrupted:

```
.../vendor/ruby/2.3.0/gems/net-http2-0.18.2/lib/net-http2/client.rb:59:in `sleep'
.../vendor/ruby/2.3.0/gems/net-http2-0.18.2/lib/net-http2/client.rb:59:in `join'
.../vendor/ruby/2.3.0/gems/apnotic-1.6.0/lib/apnotic/connection.rb:76:in `join'
```

In the attempt to troubleshoot, I have reduced a batch of around 30k pushes on a connection, to doing batches of 200, and re-building the connection for each batch. However, I still run into this "sleep forever" behavior on .join in about 1/4 of the runs of the job.

**Comment by pbhogan** [comment]
I'm having a similar hang on sends (not async, and using individual connections, not connection pool, although the problem happens with the pool also). It just seems to get stuck on the send forever.

So far, adding an explicit timeout to the send call seems to be working, but it remains to be seen if this is a long term fix. 

```
notification = Apnotic::Notification.new token
# ...
response = connection.push notification, timeout: 5
connection.close
```

Does the internal HTTP2 call without a specified timeout just wait indefinitely and that's what's causing these hangs?
https://github.com/ostinelli/apnotic/blob/b71af58e7eb610c2bd734686224dd60a53efe231/lib/apnotic/connection.rb#L45-L49
