### ISSUE TITLE
EOF error

### ISSUE THREAD

**Issue by petervandeput** [ostinelli/apnotic#93]
Follow all instructions and created the pem file according to the documentation.
when trying to send a notification it will throw following error

```
#<Thread:0x0000000118c6dae0@/Users/petervandeput/Documents/Development/rails/ariki/vendor/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:108 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        5: from /Users/petervandeput/Documents/Development/rails/ariki/vendor/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:110:in `block (2 levels) in ensure_open'
        4: from /Users/petervandeput/Documents/Development/rails/ariki/vendor/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:138:in `socket_loop'
        3: from /Users/petervandeput/Documents/Development/rails/ariki/vendor/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:138:in `loop'
        2: from /Users/petervandeput/Documents/Development/rails/ariki/vendor/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:141:in `block in socket_loop'
        1: from /Users/petervandeput/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:182:in `read_nonblock'
/Users/petervandeput/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:182:in `sysread_nonblock': end of file reached (EOFError)
        2: from /Users/petervandeput/Documents/Development/rails/ariki/vendor/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:109:in `block (2 levels) in ensure_open'
        1: from /Users/petervandeput/Documents/Development/rails/ariki/vendor/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:115:in `rescue in block (2 levels) in ensure_open'
/Users/petervandeput/Documents/Development/rails/ariki/vendor/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:130:in `callback_or_raise': Socket was remotely closed (SocketError)
Traceback (most recent call last):
SocketError (Socket was remotely closed)

```

**Comment by PedramVeisi** [comment]
I have the same issue. Connecting to the right server (dev/prod) and still getting this error. Did you figure it out?

**Comment by nbastoWM** [comment]
I had that same error but I was using a development certificate with Connection.new instead of Connection.development.
Try to alternate between development and production certificates to see if that's the problem.

**Comment by benubois** [comment]
Closing due to inactivity.
